owner: syfrtech # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Syfr
    url: https://syfr.app
  - name: Syfr Dev Playground
    url: https://develop-api.syfr.app/playground

status-website:
  cname: status.syfr.app
  logoUrl: https://avatars.githubusercontent.com/u/71347930
  favicon: https://avatars.githubusercontent.com/u/71347930
  name: Syfr
  introTitle: "View our uptime history"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
i18n:
  footer: "[Learn about Syfr](https://syfr.app)"
